language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/.npm

php:
    - 7.0
    - 7.1

env:
    global:
        - SYMFONY_ENV=test

matrix:
    fast_finish: true
    include:
        - php: 7.0
          env: COVERAGE=true

before_install:
    - . $HOME/.nvm/nvm.sh
    - nvm install 6
    - nvm use 6
    - npm install -g bower gulp-cli

install:
    - make COMPOSEROPTS="--prefer-dist --no-interaction" deps

before_script:
    - make setup
    - make GULPOPTS="--env production" frontend

script:
    - make test
