version: '2'

services:
    db:
        extends:
            file: etc/docker/common/db/docker-compose.yml
            service: db
        volumes:
            - ./var/docker/prod/mysql:/var/lib/mysql

    app:
        build: .
        links:
            - db
        volumes:
            - ./var/docker/prod/app/uploads:/app/var/uploads
            - ./var/docker/prod/app/web:/app/web
        environment:
            SYMFONY_ENV: prod
            SYMFONY__DATABASE_HOST: db

    web:
        image: webplates/symfony-nginx
        ports:
            - 80
        links:
            - app
        volumes:
            - ./var/docker/prod/app/uploads:/app/var/uploads
            - ./var/docker/prod/app/web:/app/web
