version: '2'

services:
    data:
        image: alpine
        command: /bin/true
        volumes:
            - .:/app

    frontend:
        build: etc/docker/dev/frontend
        volumes_from:
            - data
        environment:
            NPM_CONFIG_PREFIX: /app/var/docker/dev/npm/prefix
            NPM_CONFIG_CACHE: /app/var/docker/dev/npm/cache

    db:
        extends:
            file: etc/docker/common/db/docker-compose.yml
            service: db
        volumes:
            - ./var/docker/dev/mysql:/var/lib/mysql

    app: &app
        build: etc/docker/dev/app
        volumes_from:
            - data
        links:
            - db
            - blackfire
        environment:
            COMPOSER_HOME: /app/var/docker/dev/composer

    web: &web
        build: etc/docker/dev/web
        ports:
            - 80
        links:
            - app
        volumes_from:
            - data

    app_debug:
        <<: *app
        build:
            context: etc/docker/dev/app
            args:
               USE_XDEBUG: "yes"

    web_debug:
        <<: *web
        links:
            - app_debug:app

    # Set your blackfire IDs and tokens as environment variables
    # in docker-compose.override.yml before building the containers.
    # You can find your IDs and tokens in your account profile
    # https://blackfire.io/account or on the blackfire docker
    # integration page: https://blackfire.io/docs/integrations/docker
    blackfire:
        image: blackfire/blackfire
