---
server:
    install: '1'
    timezone: UTC
    locale: hu_HU.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: symfony.dev, ip: 192.168.33.99, memory: '1024', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant/web
    docindex: app_vagrant.php
    servername: symfony.dev
mysql:
    install: '1'
    root_password: ''
    database: symfony
    user: symfony
    password: symfony
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-fpm, php5-cli, php5-intl, php5-mcrypt, php5-curl, php5-gd, php5-mysql]
xdebug:
    install: '1'
composer:
    install: '1'
