---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  register: current_hostname

- name: Add MariaDB GPG Key
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xF1656F24C74CD1D8

- name: Add MariaDB Repository
  apt_repository: repo='deb http://ams2.mirrors.digitalocean.com/mariadb/repo/10.1/ubuntu {{ ansible_distribution_release }} main' state=present update_cache=yes

- name: Install MariaDB
  apt: pkg={{ item }} state=latest
  with_items:
    - mariadb-server
    - python-mysqldb

- name: Enable MariaDB
  service: name=mysql enabled=yes

- name: Update root password for all root accounts
  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ mariadb.root_password }} login_user=root login_password={{ mariadb.root_password }}
  with_items:
    - "{{ current_hostname.stdout | lower }}"
    - 127.0.0.1
    - ::1
    - localhost
    - db

- name: Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent login_user=root login_password={{ mariadb.root_password }}
  with_items:
    - localhost
    - "{{ current_hostname.stdout | lower }}"

- name: Create databases
  mysql_db: name={{ mariadb.database }} state=present login_user=root login_password={{ mariadb.root_password }}

- name: Create users
  mysql_user: name={{ mariadb.user }} password={{ mariadb.password }} priv={{ mariadb.database }}.*:ALL state=present login_user=root login_password={{ mariadb.root_password }}

- name: Add db to /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1 db' line='127.0.0.1 db' owner=root group=root mode=0644
